import CityImage from "../assets/zones/city.png";
import ClassicImage from "../assets/zones/classic.png";
import DessertImage from "../assets/zones/desert.png";
import FlowerImage from "../assets/zones/flower.png";
import GroceryImage from "../assets/zones/grocery.png";
import NightImage from "../assets/zones/night.png";
import OverskyImage from "../assets/zones/oversky.png";
import RanchImage from "../assets/zones/ranch.png";
import SeaImage from "../assets/zones/sea.png";
import SkyImage from "../assets/zones/sky.png";
import SnowImage from "../assets/zones/snow.png";
import SpaceImage from "../assets/zones/space.png";
import TheaterImage from "../assets/zones/theater.png";
import UndergroundImage from "../assets/zones/underground.png";
import UnderseaImage from "../assets/zones/undersea.png";
import UnknownImage from "../assets/zones/unknown.png";
import VolcanImage from "../assets/zones/volcan.png";
import { OwnZone, PokemonChance, PokemonZone } from "../types/utilTypes";

const PokemonZones: { [key in OwnZone]: PokemonZone } = {
  city: { name: "City", image: CityImage },
  classic: { name: "Classic", image: ClassicImage },
  dessert: { name: "Dessert", image: DessertImage },
  flower: { name: "Flower", image: FlowerImage },
  grocery: { name: "Grocery", image: GroceryImage },
  night: { name: "Night", image: NightImage },
  oversky: { name: "Oversky", image: OverskyImage },
  ranch: { name: "Ranch", image: RanchImage },
  sea: { name: "Sea", image: SeaImage },
  sky: { name: "Sky", image: SkyImage },
  snow: { name: "Snow", image: SnowImage },
  space: { name: "Space", image: SpaceImage },
  theater: { name: "Theater", image: TheaterImage },
  underground: { name: "Underground", image: UndergroundImage },
  undersea: { name: "Undersea", image: UnderseaImage },
  unknown: { name: "Unknwon", image: UnknownImage },
  volcan: { name: "Volcan", image: VolcanImage },
};

export const ZonesByProgress: OwnZone[][] = [
  ["ranch"], //Start
  ["underground", "dessert"], // Rock
  ["sea", "sky"], // Water
  ["night", "theater"], // Electric
  ["city", "flower"], // Plant
  ["oversky", "snow"], //Poisson
  ["grocery", "classic"], //Psiquic
  ["volcan", "undersea"], //Fire
  ["unknown", "space"], //Ground
];

export const PokemonHabitat: { [key in OwnZone]: PokemonChance[] } = {
  ranch: [
    { index: 1, chance: 5, name: "bulbasaur" },
    { index: 4, chance: 5, name: "charmander" },
    { index: 7, chance: 5, name: "squirtle" },
    { index: 10, chance: 20, name: "caterpie" },
    { index: 11, chance: 15, name: "metapod" },
    { index: 13, chance: 20, name: "weedle" },
    { index: 14, chance: 15, name: "kakuna" },
    { index: 16, chance: 15, name: "pidgey" },
    { index: 19, chance: 15, name: "rattata" },
    { index: 21, chance: 10, name: "spearow" },
    { index: 39, chance: 10, name: "jigglypuff" },
    { index: 52, chance: 10, name: "meowth" },
    { index: 129, chance: 10, name: "magikarp" },
    { index: 133, chance: 10, name: "eevee" },
    { index: 152, chance: 10, name: "chikorita" },
    { index: 155, chance: 10, name: "cyndaquil" },
    { index: 158, chance: 10, name: "totodile" },
    { index: 161, chance: 10, name: "sentret" },
    { index: 165, chance: 10, name: "ledyba" },
    { index: 167, chance: 10, name: "spinarak" },
    { index: 172, chance: 10, name: "pichu" },
    { index: 173, chance: 10, name: "cleffa" },
    { index: 174, chance: 10, name: "igglybuff" },
    { index: 175, chance: 10, name: "togepi" },
    { index: 179, chance: 10, name: "mareep" },
    { index: 187, chance: 10, name: "hoppip" },
    { index: 190, chance: 10, name: "aipom" },
    { index: 191, chance: 10, name: "sunkern" },
  ],

  underground: [
    { index: 23, chance: 10, name: "ekans" },
    { index: 27, chance: 10, name: "sandshrew" },
    { index: 35, chance: 10, name: "clefairy" },
    { index: 41, chance: 10, name: "zubat" },
    { index: 43, chance: 10, name: "oddish" },
    { index: 46, chance: 10, name: "paras" },
    { index: 50, chance: 10, name: "diglett" },
    { index: 74, chance: 10, name: "geodude" },
    { index: 95, chance: 10, name: "onix" },
    { index: 201, chance: 10, name: "unown" },
    { index: 218, chance: 10, name: "slugma" },
    { index: 246, chance: 5, name: "larvitar" },
  ],
  dessert: [
    { index: 25, chance: 10, name: "pikachu" },
    { index: 29, chance: 10, name: "nidoran-f" },
    { index: 32, chance: 10, name: "nidoran-m" },
    { index: 37, chance: 10, name: "vulpix" },
    { index: 48, chance: 10, name: "venonat" },
    { index: 56, chance: 10, name: "mankey" },
    { index: 58, chance: 10, name: "growlithe" },
    { index: 66, chance: 10, name: "machop" },
    { index: 69, chance: 10, name: "bellsprout" },
    { index: 92, chance: 10, name: "gastly" },
    { index: 104, chance: 5, name: "cubone" },
    { index: 177, chance: 5, name: "natu" },
    { index: 220, chance: 5, name: "swinub" },
    { index: 236, chance: 5, name: "tyrogue" },
    { index: 238, chance: 5, name: "smoochum" },
    { index: 239, chance: 5, name: "elekid" },
    { index: 240, chance: 5, name: "magby" },
  ],

  sea: [
    { index: 54, chance: 10, name: "psyduck" },
    { index: 60, chance: 10, name: "poliwag" },
    { index: 61, chance: 10, name: "poliwhirl" },
    { index: 72, chance: 10, name: "tentacool" },
    { index: 79, chance: 10, name: "slowpoke" },
    { index: 86, chance: 10, name: "seel" },
    { index: 90, chance: 10, name: "shellder" },
    { index: 98, chance: 10, name: "krabby" },
    { index: 116, chance: 10, name: "horsea" },
    { index: 118, chance: 10, name: "goldeen" },
    { index: 120, chance: 10, name: "staryu" },
    { index: 138, chance: 10, name: "omanyte" },
    { index: 140, chance: 10, name: "kabuto" },
    { index: 147, chance: 5, name: "dratini" },
    { index: 170, chance: 10, name: "chinchou" },
    { index: 183, chance: 10, name: "marill" },
    { index: 194, chance: 10, name: "wooper" },
    { index: 222, chance: 10, name: "corsola" },
    { index: 223, chance: 10, name: "remoraid" },
  ],
  sky: [
    { index: 17, chance: 5, name: "pidgeotto" },
    { index: 22, chance: 5, name: "fearow" },
    { index: 81, chance: 5, name: "magnemite" },
    { index: 83, chance: 5, name: "farfetchd" },
    { index: 109, chance: 10, name: "koffing" },
    { index: 163, chance: 10, name: "hoothoot" },
    { index: 188, chance: 10, name: "skiploom" },
  ],

  night: [
    { index: 30, chance: 10, name: "nidorina" },
    { index: 33, chance: 10, name: "nidorino" },
    { index: 42, chance: 10, name: "golbat" },
    { index: 44, chance: 10, name: "gloom" },
    { index: 70, chance: 10, name: "weepinbell" },
    { index: 88, chance: 10, name: "grimer" },
    { index: 93, chance: 10, name: "haunter" },
    { index: 96, chance: 10, name: "drowzee" },
    { index: 111, chance: 10, name: "rhyhorn" },
    { index: 193, chance: 10, name: "yanma" },
    { index: 198, chance: 10, name: "murkrow" },
    { index: 204, chance: 5, name: "pineco" },
    { index: 206, chance: 10, name: "dunsparce" },
    { index: 207, chance: 10, name: "gligar" },
    { index: 228, chance: 10, name: "houndour" },
  ],
  theater: [
    { index: 20, chance: 5, name: "raticate" },
    { index: 57, chance: 5, name: "primeape" },
    { index: 63, chance: 10, name: "abra" },
    { index: 64, chance: 10, name: "kadabra" },
    { index: 67, chance: 10, name: "machoke" },
    { index: 77, chance: 10, name: "ponyta" },
    { index: 84, chance: 5, name: "doduo" },
    { index: 100, chance: 5, name: "voltorb" },
    { index: 162, chance: 10, name: "furret" },
    { index: 213, chance: 10, name: "shuckle" },
    { index: 235, chance: 5, name: "smeargle" },
  ],

  city: [
    { index: 24, chance: 10, name: "arbok" },
    { index: 49, chance: 10, name: "venomoth" },
    { index: 82, chance: 5, name: "magneton" },
    { index: 89, chance: 10, name: "muk" },
    { index: 97, chance: 10, name: "hypno" },
    { index: 105, chance: 10, name: "marowak" },
    { index: 110, chance: 10, name: "weezing" },
    { index: 132, chance: 10, name: "ditto" },
    { index: 164, chance: 10, name: "noctowl" },
    { index: 168, chance: 10, name: "ariados" },
    { index: 171, chance: 10, name: "lanturn" },
    { index: 189, chance: 10, name: "jumpluff" },
    { index: 200, chance: 10, name: "misdreavus" },
    { index: 209, chance: 10, name: "snubbull" },
    { index: 229, chance: 10, name: "houndoom" },
    { index: 231, chance: 10, name: "phanpy" },
  ],
  flower: [
    { index: 2, chance: 5, name: "ivysaur" },
    { index: 5, chance: 5, name: "charmeleon" },
    { index: 8, chance: 5, name: "wartortle" },
    { index: 12, chance: 5, name: "butterfree" },
    { index: 15, chance: 5, name: "beedrill" },
    { index: 47, chance: 5, name: "parasect" },
    { index: 102, chance: 5, name: "exeggcute" },
    { index: 114, chance: 5, name: "tangela" },
    { index: 119, chance: 10, name: "seaking" },
    { index: 123, chance: 10, name: "scyther" },
    { index: 127, chance: 10, name: "pinsir" },
    { index: 153, chance: 10, name: "bayleef" },
    { index: 156, chance: 10, name: "quilava" },
    { index: 159, chance: 10, name: "croconaw" },
    { index: 166, chance: 10, name: "ledian" },
    { index: 180, chance: 10, name: "flaaffy" },
    { index: 185, chance: 10, name: "sudowoodo" },
    { index: 192, chance: 10, name: "sunflora" },
    { index: 203, chance: 5, name: "girafarig" },
    { index: 205, chance: 5, name: "forretress" },
    { index: 212, chance: 5, name: "scizor" },
    { index: 214, chance: 5, name: "heracross" },
    { index: 216, chance: 5, name: "teddiursa" },
    { index: 234, chance: 5, name: "stantler" },
    { index: 241, chance: 5, name: "miltank" },
  ],

  oversky: [
    { index: 18, chance: 5, name: "pidgeot" },
    { index: 36, chance: 5, name: "clefable" },
    { index: 40, chance: 5, name: "wigglytuff" },
    { index: 113, chance: 5, name: "chansey" },
    { index: 148, chance: 5, name: "dragonair" },
    { index: 176, chance: 10, name: "togetic" },
    { index: 178, chance: 5, name: "xatu" },
    { index: 184, chance: 10, name: "azumarill" },
    { index: 227, chance: 10, name: "skarmory" },
    { index: 242, chance: 10, name: "blissey" },
  ],
  snow: [
    { index: 28, chance: 10, name: "sandslash" },
    { index: 75, chance: 10, name: "graveler" },
    { index: 87, chance: 10, name: "dewgong" },
    { index: 91, chance: 10, name: "cloyster" },
    { index: 117, chance: 10, name: "seadra" },
    { index: 124, chance: 10, name: "jynx" },
    { index: 215, chance: 5, name: "sneasel" },
    { index: 221, chance: 5, name: "piloswine" },
    { index: 225, chance: 5, name: "delibird" },
  ],

  grocery: [
    { index: 26, chance: 10, name: "raichu" },
    { index: 38, chance: 10, name: "ninetales" },
    { index: 45, chance: 10, name: "vileplume" },
    { index: 53, chance: 10, name: "persian" },
    { index: 71, chance: 10, name: "victreebel" },
    { index: 85, chance: 5, name: "dodrio" },
    { index: 94, chance: 10, name: "gengar" },
    { index: 101, chance: 5, name: "electrode" },
    { index: 108, chance: 10, name: "lickitung" },
    { index: 122, chance: 10, name: "mr-mime" },
    { index: 125, chance: 10, name: "electabuzz" },
    { index: 135, chance: 10, name: "jolteon" },
    { index: 143, chance: 10, name: "snorlax" },
    { index: 181, chance: 10, name: "ampharos" },
    { index: 195, chance: 10, name: "quagsire" },
    { index: 196, chance: 10, name: "espeon" },
    { index: 210, chance: 10, name: "granbull" },
    { index: 217, chance: 5, name: "ursaring" },
  ],
  classic: [
    { index: 3, chance: 5, name: "venusaur" },
    { index: 31, chance: 10, name: "nidoqueen" },
    { index: 34, chance: 10, name: "nidoking" },
    { index: 51, chance: 10, name: "dugtrio" },
    { index: 55, chance: 10, name: "golduck" },
    { index: 68, chance: 10, name: "machamp" },
    { index: 78, chance: 10, name: "rapidash" },
    { index: 103, chance: 5, name: "exeggutor" },
    { index: 106, chance: 10, name: "hitmonlee" },
    { index: 107, chance: 10, name: "hitmonchan" },
    { index: 128, chance: 10, name: "tauros" },
    { index: 154, chance: 10, name: "meganium" },
    { index: 169, chance: 10, name: "crobat" },
    { index: 182, chance: 10, name: "bellossom" },
    { index: 186, chance: 10, name: "politoed" },
    { index: 197, chance: 10, name: "umbreon" },
    { index: 237, chance: 10, name: "hitmontop" },
  ],

  volcan: [
    { index: 6, chance: 5, name: "charizard" },
    { index: 59, chance: 5, name: "arcanine" },
    { index: 76, chance: 10, name: "golem" },
    { index: 112, chance: 10, name: "rhydon" },
    { index: 115, chance: 10, name: "kangaskhan" },
    { index: 126, chance: 10, name: "magmar" },
    { index: 136, chance: 10, name: "flareon" },
    { index: 142, chance: 10, name: "aerodactyl" },
    { index: 157, chance: 10, name: "typhlosion" },
    { index: 208, chance: 10, name: "steelix" },
    { index: 219, chance: 10, name: "magcargo" },
    { index: 232, chance: 10, name: "donphan" },
    { index: 247, chance: 5, name: "pupitar" },
  ],
  undersea: [
    { index: 9, chance: 5, name: "blastoise" },
    { index: 62, chance: 10, name: "poliwrath" },
    { index: 73, chance: 10, name: "tentacruel" },
    { index: 80, chance: 10, name: "slowbro" },
    { index: 99, chance: 10, name: "kingler" },
    { index: 121, chance: 10, name: "starmie" },
    { index: 130, chance: 10, name: "gyarados" },
    { index: 131, chance: 10, name: "lapras" },
    { index: 134, chance: 10, name: "vaporeon" },
    { index: 139, chance: 10, name: "omastar" },
    { index: 141, chance: 10, name: "kabutops" },
    { index: 160, chance: 10, name: "feraligatr" },
    { index: 199, chance: 10, name: "slowking" },
    { index: 211, chance: 10, name: "qwilfish" },
    { index: 224, chance: 10, name: "octillery" },
    { index: 226, chance: 5, name: "mantine" },
    { index: 230, chance: 5, name: "kingdra" },
  ],

  unknown: [
    { index: 65, chance: 5, name: "alakazam" },
    { index: 144, chance: 5, name: "articuno" },
    { index: 145, chance: 5, name: "zapdos" },
    { index: 146, chance: 5, name: "moltres" },
    { index: 149, chance: 5, name: "dragonite" },
    { index: 202, chance: 5, name: "wobbuffet" },
    { index: 233, chance: 5, name: "porygon2" },
    { index: 243, chance: 5, name: "raikou" },
    { index: 244, chance: 5, name: "entei" },
    { index: 245, chance: 5, name: "suicune" },
    { index: 248, chance: 5, name: "tyranitar" },
    { index: 249, chance: 5, name: "lugia" },
    { index: 250, chance: 5, name: "ho-oh" },
  ],
  space: [
    { index: 150, chance: 5, name: "mewtwo" },
    { index: 151, chance: 5, name: "mew" },
    { index: 251, chance: 5, name: "celebi" },
  ],
};

export default PokemonZones;
